# Configuration for golangci-lint
# See: https://golangci-lint.run/usage/configuration/

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - gocyclo
    - dupl

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "G204" # Audit use of command execution
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocyclo

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - disableStutteringCheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
